all:
	> ../infogetmatrix.m
	cat \
		infogetmatrix-header1.m \
		header-example-infostr.m \
		infogetmatrix-header2.m \
		infogetmatrix-body.m \
		regexpescape.m \
		csv2cell.m \
		infogetmatrix-tests.m \
	>> ../infogetmatrix.m
	
	> ../infogetnumber.m
	cat \
		infogetnumber-header1.m \
		header-example-infostr.m \
		infogetnumber-header2.m \
		infogetnumber-body.m \
		regexpescape.m \
		infogetnumber-tests.m \
	>> ../infogetnumber.m
	
	> ../infogetsection.m
	cat \
		infogetsection-header1.m \
		header-example-infostr.m \
		infogetsection-header2.m \
		infogetsection-body.m \
		infogetsection-tests.m \
	>> ../infogetsection.m
	
	> ../infogettext.m
	cat \
		infogettext-header1.m \
		header-example-infostr.m \
		infogettext-header2.m \
		infogettext-body.m \
		regexpescape.m \
		infogettext-tests.m \
	>> ../infogettext.m
	
	> ../infogettextmatrix.m
	cat \
		infogettextmatrix-header1.m \
		header-example-infostr.m \
		infogettextmatrix-header2.m \
		infogettextmatrix-body.m \
		regexpescape.m \
		csv2cell.m \
		infogettextmatrix-tests.m \
	>> ../infogettextmatrix.m
	
	> ../infogettime.m
	cat \
		infogettime-header.m \
		infogettime-body.m \
		regexpescape.m \
		infogettime-tests.m \
	>> ../infogettime.m
	
	> ../infoload.m
	cat \
		infoload-header.m \
		infoload-body.m \
		infoload-tests.m \
	>> ../infoload.m
	
	> ../infosave.m
	cat \
		infosave-header.m \
		infosave-body.m \
		infosave-tests.m \
	>> ../infosave.m
	
	> ../infosetmatrix.m
	cat \
		infosetmatrix-header.m \
		infosetmatrix-body.m \
		infosetmatrix-tests.m \
	>> ../infosetmatrix.m
	
	> ../infosetnumber.m
	cat \
		infosetnumber-header.m \
		infosetnumber-body.m \
		infosetnumber-tests.m \
	>> ../infosetnumber.m
	
	> ../infosetsection.m
	cat \
		infosetsection-header.m \
		infosetsection-body.m \
		infosetsection-tests.m \
	>> ../infosetsection.m
	
	> ../infosettext.m
	cat \
		infosettext-header.m \
		infosettext-body.m \
		infosettext-tests.m \
	>> ../infosettext.m
	
	> ../infosettextmatrix.m
	cat \
		infosettextmatrix-header.m \
		infosettextmatrix-body.m \
		infosettextmatrix-tests.m \
	>> ../infosettextmatrix.m
	
	> ../infosettime.m
	cat \
		infosettime-header.m \
		infosettime-body.m \
		infosettime-tests.m \
	>> ../infosettime.m
	
